apiVersion: v1
kind: Service
metadata:
  name: evidra-gitops
  labels:
    app.kubernetes.io/name: evidra-gitops
spec:
  selector:
    app.kubernetes.io/name: evidra-gitops
  ports:
    - name: http
      port: 80
      targetPort: http
