apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: evidra-gitops
  labels:
    app.kubernetes.io/name: evidra-gitops
spec:
  to:
    kind: Service
    name: evidra-gitops
  port:
    targetPort: http
  tls:
    termination: edge
