apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: evidra-gitops-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://example.com/your-org/evidra-gitops.git
    targetRevision: main
    path: deploy/k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: evidra-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
